name: Scheduled Data Release with Conda

on:
  schedule:
    # Runs every Sunday at 03:00 UTC. Adjust as needed.
    - cron: '0 3 * * 0'
  # Allows you to run this workflow manually from the Actions tab for testing
  workflow_dispatch:

jobs:
  build-export-and-release:
    runs-on: ubuntu-latest
    # Required to create/update a release and push a tag
    permissions:
      contents: write

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Micromamba environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Install local project package
        run: pip install . --no-deps
        shell: bash -el {0}

      - name: Run the export script
        run: python main_export.py --dest ./output
        shell: bash -el {0}

      - name: Archive the generated files
        run: |
          cd output
          zip -r ../data-export.zip mj approval
          cd ..
        shell: bash -el {0}

      - name: Copy compact files for direct access
        run: |
          cp output/approval/latest_survey_approval_compact.json ./ || true
          cp output/approval/latest_survey_approval.csv ./ || true
          cp output/mj/latest_survey_mj_compact.json ./ || true
          cp output/mj/latest_survey_mj.csv ./ || true
        shell: bash -el {0}

      - name: Update the 'latest-data' Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git tag -f latest-data -m "Latest data export"
          git push -f origin latest-data
        shell: bash -el {0}

      - name: Update or Create Release
        uses: ncipollo/release-action@v1
        with:
          # This tells the action to attach the files to the release
          artifacts: |
            data-export.zip
            latest_survey_approval_compact.json
            latest_survey_approval.csv
            latest_survey_mj_compact.json
            latest_survey_mj.csv
          # This tells the action to update the release if it already exists
          allowUpdates: true
          # This tells the action to use the static tag we just pushed
          tag: latest-data
          # This ensures old versions of the asset are replaced
          replacesArtifacts: true
